sudo: false

language: node_js

node_js:
  - 6.14.0 # Cloud Functions Runtime
  - 9
  - 10

notifications:
  email:
    # Only send notifications when travis status changes
    on_failure: change
    on_success: change

cache:
  directories:
    - node_modules

branches:
  only:
    - master

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    node: '10'
    branch: 'master'

script:
  - npm run lint
  - npm run test:cov

after_success:
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run codecov
